-- In here you can add two team taunts without seperating them.
local taunts = {}

-- Begin Table: Hunter
taunts.Hunter = {
	["Another one bites the dust"]	=	"taunts/custom/bites the dust.wav",
	["I see ya"]					=	"taunts/custom/I see you.wav",
	["(Vegeta) what are you doing here"]	=	"taunts/custom/vegeta what are you doing here.wav",
	["You shall not pass!"]			=	"taunts/custom/you shall not pass.wav",
	["100 barrels of beer"]			=	"taunts/custom/100 barrels of beer.wav",
	["Do you feel lucky"]			=	"taunts/custom/do you feel lucky.wav",
	["FBI open up"]					=	"taunts/custom/fbi open up.wav",
	["Silence! I kill you"]			=	"taunts/custom/silence i kill you.wav",
	["Why are you running"]			=	"taunts/custom/why are you running.wav",
	["Surprise mofo"]				=	"taunts/custom/Surprise mofo.wav",	
	["I have beautiful eyes"]		=	"taunts/custom/beautiful eyes.wav",
	["I'll keep killing you"]		=	"taunts/custom/drunk demo.wav",
	["English, do you speak it"]	=	"taunts/custom/EnglishMofo.wav",
	["you're already dead"]			=	"taunts/custom/omae wa.wav",
	["Stare at each other"]			=	"taunts/custom/pretty.wav",
	["Here's Johnny"]				=	"taunts/custom/shining_heres_johnny.wav",
	["Die mofo die!"]				=	"taunts/custom/die mf die.wav",
	["Die"]							=	"taunts/custom/Die.wav",
	["Allah akbar"]					=	"taunts/custom/allah.wav",
	["Guuuh!"]						=	"vo/k_lab/ba_guh.wav",
	["If you See Dr. Breen"]		= 	"vo/streetwar/rubble/ba_tellbreen.wav"
	-- Add more Hunters Taunt here...
}
-- Begin Table: Props
taunts.Props = {
	["C4"]							=	"taunts/custom/c4.wav",
	["*Click* Noice"]				=	"taunts/custom/click noice.wav",
	["f*ck ssj"]					=	"taunts/custom/fk ssj.wav",
	["I feel good"]					=	"taunts/custom/i feel good.wav",
	["It's pikachu"]				=	"taunts/custom/its pikachu.wav",
	["Look at my horse"]			=	"taunts/custom/look at my horse.wav",
	["My swamp"]					=	"taunts/custom/my swamp.wav",
	["Noice"]						=	"taunts/custom/noice.wav",
	["Poker face"]					=	"taunts/custom/poker face.wav",
	["Retarded laugh"]				=	"taunts/custom/retarded laugh.wav",
	["Smooth criminal"]				=	"taunts/custom/smooth criminal.wav",
	["(Torgue) explosions!?"]		=	"taunts/custom/torgue explosions.wav",
	["Tunak tun"]					=	"taunts/custom/tunak tun.wav",
	["(Vegeta) fuuuu"]				=	"taunts/custom/vegeta fuuuu.wav",
	["We like to party"]			=	"taunts/custom/we like to party.wav",
	["Welcome to the rice fields"]	=	"taunts/custom/welcome to the rice fields.wav",
	["You touch my tralala"]		=	"taunts/custom/you touch my tralala.wav",
	["AAAAHHHH song"]				=	"taunts/custom/aaaaaaaaa.wav",
	["Crawling in my crawl"]		=	"taunts/custom/crawling in my crawl.wav",
	["NFS Nine Thou"]				=	"taunts/custom/NFS nine thou.wav",
	["Goku goes SSJ3 (60+sec)"]		=	"taunts/custom/SSJ3.wav",
	["WTF Boom"]					=	"taunts/custom/wtf boom.wav",
	["Wtf are you looking at"]		=	"taunts/custom/wtf are you lookin at.wav",
	["Running in the 90s"]			=	"taunts/custom/running in the 90s.wav",
	["Sniper laugh"]				=	"taunts/custom/sniper laugh.wav",
	["Sexy sax"]					=	"taunts/custom/Sexy sax.wav",
	["Over 9000"]					=	"taunts/custom/over9000.wav",
	["Badum tss"]					=	"taunts/custom/badum tss.wav",
	["FF7 win"]						=	"taunts/custom/ff7 win.wav",
	["Kamehameha"]					=	"taunts/custom/kamehameha.wav",
	["Shoot me now"]				=	"taunts/custom/BB Shoot him now.wav",
	["Call on me"]					=	"taunts/custom/Call on me.wav",
	["Follow my voice"]				=	"taunts/custom/CLP_MyVoice.wav",
	["Fus ro dah"]					=	"taunts/custom/fus ro dah.wav",
	["Gay frogs"]					=	"taunts/custom/Gay Frogs.wav",
	["Good luck"]					=	"taunts/custom/GLYF.wav",
	["Kill me"]						=	"taunts/custom/Kill me.wav",
	["Hello"]						=	"taunts/custom/medic hello.wav",
	["Ready to die"]				=	"taunts/custom/Ready to die.wav",
	["Smile Sweet Cyka"]			=	"taunts/custom/Smile Sweet.wav",
	["Team is babies"]				=	"taunts/custom/team babies.wav",
	["YEAAAAAH"]					=	"taunts/custom/yeaaah.wav",
	["Begone thot"]					=	"taunts/custom/begone thot.wav",
	["Best pirate I've ever seen"]	=	"taunts/custom/best pirate.wav",
	["Big Smoke oh my god"]			=	"taunts/custom/bs oh my god.wav",
	["Big Smoke OOH"]				=	"taunts/custom/bs ooh.wav",
	["Surprise buttsex"]			=	"taunts/custom/buttsex.wav",
	["Discord notification"]		=	"taunts/custom/discord notification.wav",
	["Do it"]						=	"taunts/custom/do it.wav",
	["Drop it"]						=	"taunts/custom/drop it.wav",
	["Foo"]							=	"taunts/custom/foo.wav",
	["Fuck fuck fuck fuck"]			=	"taunts/custom/fuck fuck.wav",
	["GWA GWA GWA"]					=	"taunts/custom/gwagwa.wav",
	["Helmet headshot"]				=	"taunts/custom/headshot.wav",
	["Inhuman reactions"]			=	"taunts/custom/inhuman reactions.wav",
	["Loud scream"]					=	"taunts/custom/loud scream.wav",
	["Mexican laugh"]				=	"taunts/custom/mexican laugh.wav",
	["Pateta caindo"]				=	"taunts/custom/pateta caindo.wav",
	["Rap god"]						=	"taunts/custom/rap god.wav",
	["Shrek button"]				=	"taunts/custom/shrek button.wav",
	["Slow oof"]					=	"taunts/custom/slow oof.wav",
	["Thug life"]					=	"taunts/custom/thug life.wav",
	["To be continued"]				=	"taunts/custom/to be continued.wav",
	["What is going on"]			=	"taunts/custom/what is going on.wav",
	["What wtf"]					=	"taunts/custom/what wtf.wav",
	["Why are we still here"]		=	"taunts/custom/why are we still here.wav",
	["Why are you gay"]				=	"taunts/custom/why are you gay.wav",
	["Yes Yes Yes Yes Yes"]			=	"taunts/custom/yes yes.wav",
	["Spanking"]					=	"taunts/custom/spanking.wav",
	["Let me in"]					=	"taunts/custom/let me in.wav",
	["Way away from here"]			=	"taunts/custom/way away.wav",
	["Door's stuck"]				=	"taunts/custom/door stuck.wav",
	["Giggity goo"]					=	"taunts/custom/giggity goo.wav",
	["Alabama cousin"]				=	"taunts/custom/a_cousin.wav",
	["Windows XP Shutdown"]			=	"taunts/ph_enhanced/ext_xp_off.wav",
	["Windows XP Startup"]			=	"taunts/ph_enhanced/ext_xp_start.wav",
	["_God Damn It Why"]	=	"taunts/custom/god_dammit_why.wav"
	-- Add more Props Taunt here...
}

-- if everything's done with above, let's add them as the list.
-- They will be automatically added as soon as the game loads!
for propTaunt,propPath in pairs(taunts.Props) do list.Set("PHE.CustomPropTaunts", propTaunt, propPath) end
for hunterTaunt,hunterPath in pairs(taunts.Hunter) do list.Set("PHE.CustomHunterTaunts", hunterTaunt, hunterPath) end


-- You can also add your custom taunts outside from this scope with your own [ list.Set("PHE.Custom<Prop/Hunter>Taunts", "Taunt Name", "Your Taunt Path") ]
